services:
  - type: web
    name: board-vision-backend
    env: docker
    region: oregon
    plan: free
    rootDir: board-vision-app
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PGHOST
        fromDatabase:
          name: board-vision-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: board-vision-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: board-vision-db
          property: database
      - key: PGUSER
        fromDatabase:
          name: board-vision-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: board-vision-db
          property: password
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: HUGGINGFACE_TOKEN
        sync: false

databases:
  - name: board-vision-db
    databaseName: clens_chess_db
    user: boardvision
    plan: free
    region: oregon
