services:
  - type: web
    name: board-vision-backend
    env: java
    region: oregon
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/pgn-backend-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 10000
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: board-vision-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: board-vision-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: board-vision-db
          property: password
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: HUGGINGFACE_TOKEN
        sync: false

databases:
  - name: board-vision-db
    databaseName: clens_chess_db
    user: boardvision
    plan: free
    region: oregon
